# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ansible/ansible-lint
    rev: v26.1.1
    hooks:
      - id: ansible-lint
  - repo: local
    hooks:
      - id: no_debug_comments
        name: No Debug Comments
        language: pygrep
        entry: '("""|#) ?DEBUG'
        types:
          - file
        fail_fast: false
      - id: no_fixme_comments
        name: No FIXME Comments
        language: pygrep
        entry: '("""|#) ?FIXME'
        types:
          - file
        exclude: .pre-commit-config.yaml
        fail_fast: false
      - id: no_testing_comments
        name: No Testing Comments
        language: pygrep
        entry: '("""|#) ?[A-Z0-9_]*TEST'
        types:
          - file
        exclude: '(^.pre-commit-config.yaml|^tests/docker/run.sh)'
        fail_fast: false
